"use client";
import { useEffect, useMemo, useState } from "react";
import { VOYLME_EVENTS, VOYLME_STORAGE } from "@/lib/voylme/config/storage";
export type HomeCopy={services:[string,string,string,string,string];roundTrip:string;oneWay:string;from:string;to:string;departure:string;return:string;travellers:string;traveller:string;cabinClass:string;searchFlights:string;noReturnDate:string;adultTravellers:string;selectTravellers:string;done:string;noAirports:string;economy:string;premiumEconomy:string;business:string;first:string;};
const EN:HomeCopy={services:["Flights","Hotels","Cars","Activities","Yachts"],roundTrip:"Round Trip",oneWay:"One Way",from:"From",to:"To",departure:"Departure",return:"Return",travellers:"Travellers",traveller:"Traveller",cabinClass:"Cabin class",searchFlights:"Search Flights",noReturnDate:"No return date",adultTravellers:"Adult travellers",selectTravellers:"Select 1 to 9 travellers",done:"Done",noAirports:"No matching airports found.",economy:"Economy",premiumEconomy:"Premium Economy",business:"Business",first:"First"};
const C:Record<string,HomeCopy>={
ENG:EN,ENG_US:EN,ENG_GB:EN,
ARA:{services:["رحلات","فنادق","سيارات","أنشطة","يخوت"],roundTrip:"ذهاب وعودة",oneWay:"اتجاه واحد",from:"من",to:"إلى",departure:"المغادرة",return:"العودة",travellers:"المسافرون",traveller:"مسافر",cabinClass:"درجة السفر",searchFlights:"ابحث عن رحلات",noReturnDate:"بدون عودة",adultTravellers:"المسافرون البالغون",selectTravellers:"اختر من 1 إلى 9 مسافرين",done:"تم",noAirports:"لا توجد مطارات مطابقة.",economy:"السياحية",premiumEconomy:"السياحية الممتازة",business:"رجال الأعمال",first:"الأولى"},
FRA:{services:["Vols","Hôtels","Voitures","Activités","Yachts"],roundTrip:"Aller-retour",oneWay:"Aller simple",from:"De",to:"À",departure:"Départ",return:"Retour",travellers:"Voyageurs",traveller:"Voyageur",cabinClass:"Classe",searchFlights:"Rechercher",noReturnDate:"Sans retour",adultTravellers:"Voyageurs adultes",selectTravellers:"Choisissez de 1 à 9 voyageurs",done:"Terminé",noAirports:"Aucun aéroport trouvé.",economy:"Économique",premiumEconomy:"Premium",business:"Affaires",first:"Première"},
SPA:{services:["Vuelos","Hoteles","Coches","Actividades","Yates"],roundTrip:"Ida y vuelta",oneWay:"Solo ida",from:"Desde",to:"Hasta",departure:"Salida",return:"Regreso",travellers:"Viajeros",traveller:"Viajero",cabinClass:"Clase",searchFlights:"Buscar vuelos",noReturnDate:"Sin regreso",adultTravellers:"Viajeros adultos",selectTravellers:"Elige de 1 a 9 viajeros",done:"Listo",noAirports:"No hay aeropuertos coincidentes.",economy:"Económica",premiumEconomy:"Económica Premium",business:"Business",first:"Primera"},
DEU:{services:["Flüge","Hotels","Autos","Aktivitäten","Yachten"],roundTrip:"Hin und zurück",oneWay:"Nur Hinflug",from:"Von",to:"Nach",departure:"Abflug",return:"Rückflug",travellers:"Reisende",traveller:"Reisender",cabinClass:"Klasse",searchFlights:"Flüge suchen",noReturnDate:"Kein Rückflug",adultTravellers:"Erwachsene",selectTravellers:"1 bis 9 Reisende wählen",done:"Fertig",noAirports:"Keine passenden Flughäfen.",economy:"Economy",premiumEconomy:"Premium Economy",business:"Business",first:"First"},
NLD:{services:["Vluchten","Hotels","Auto's","Activiteiten","Jachten"],roundTrip:"Retour",oneWay:"Enkele reis",from:"Van",to:"Naar",departure:"Vertrek",return:"Terug",travellers:"Reizigers",traveller:"Reiziger",cabinClass:"Klasse",searchFlights:"Vluchten zoeken",noReturnDate:"Geen retour",adultTravellers:"Volwassen reizigers",selectTravellers:"Kies 1 tot 9 reizigers",done:"Gereed",noAirports:"Geen luchthavens gevonden.",economy:"Economy",premiumEconomy:"Premium Economy",business:"Business",first:"First"},
CAT:{services:["Vols","Hotels","Cotxes","Activitats","Iots"],roundTrip:"Anada i tornada",oneWay:"Només anada",from:"Des de",to:"Fins a",departure:"Sortida",return:"Tornada",travellers:"Viatgers",traveller:"Viatger",cabinClass:"Classe",searchFlights:"Cerca vols",noReturnDate:"Sense tornada",adultTravellers:"Viatgers adults",selectTravellers:"Tria d'1 a 9 viatgers",done:"Fet",noAirports:"No s'han trobat aeroports.",economy:"Econòmica",premiumEconomy:"Econòmica Premium",business:"Business",first:"Primera"},
ITA:{services:["Voli","Hotel","Auto","Attività","Yacht"],roundTrip:"Andata e ritorno",oneWay:"Solo andata",from:"Da",to:"A",departure:"Partenza",return:"Ritorno",travellers:"Viaggiatori",traveller:"Viaggiatore",cabinClass:"Classe",searchFlights:"Cerca voli",noReturnDate:"Senza ritorno",adultTravellers:"Viaggiatori adulti",selectTravellers:"Scegli da 1 a 9 viaggiatori",done:"Fatto",noAirports:"Nessun aeroporto trovato.",economy:"Economy",premiumEconomy:"Premium Economy",business:"Business",first:"Prima"},
POR:{services:["Voos","Hotéis","Carros","Atividades","Iates"],roundTrip:"Ida e volta",oneWay:"Só ida",from:"De",to:"Para",departure:"Partida",return:"Regresso",travellers:"Viajantes",traveller:"Viajante",cabinClass:"Classe",searchFlights:"Pesquisar voos",noReturnDate:"Sem regresso",adultTravellers:"Viajantes adultos",selectTravellers:"Escolha de 1 a 9 viajantes",done:"Concluído",noAirports:"Nenhum aeroporto encontrado.",economy:"Económica",premiumEconomy:"Económica Premium",business:"Executiva",first:"Primeira"},
RUS:{services:["Рейсы","Отели","Авто","Развлечения","Яхты"],roundTrip:"Туда и обратно",oneWay:"В одну сторону",from:"Откуда",to:"Куда",departure:"Вылет",return:"Возврат",travellers:"Пассажиры",traveller:"Пассажир",cabinClass:"Класс",searchFlights:"Найти рейсы",noReturnDate:"Без возврата",adultTravellers:"Взрослые",selectTravellers:"Выберите от 1 до 9",done:"Готово",noAirports:"Аэропорты не найдены.",economy:"Эконом",premiumEconomy:"Премиум-эконом",business:"Бизнес",first:"Первый"},
TUR:{services:["Uçuşlar","Oteller","Araçlar","Aktiviteler","Yatlar"],roundTrip:"Gidiş-dönüş",oneWay:"Tek yön",from:"Nereden",to:"Nereye",departure:"Gidiş",return:"Dönüş",travellers:"Yolcular",traveller:"Yolcu",cabinClass:"Kabin",searchFlights:"Uçuş ara",noReturnDate:"Dönüş yok",adultTravellers:"Yetişkin yolcular",selectTravellers:"1-9 yolcu seçin",done:"Bitti",noAirports:"Havalimanı bulunamadı.",economy:"Ekonomi",premiumEconomy:"Premium Ekonomi",business:"Business",first:"First"},
POL:{services:["Loty","Hotele","Samochody","Atrakcje","Jachty"],roundTrip:"W obie strony",oneWay:"W jedną stronę",from:"Z",to:"Do",departure:"Wylot",return:"Powrót",travellers:"Podróżni",traveller:"Podróżny",cabinClass:"Klasa",searchFlights:"Szukaj lotów",noReturnDate:"Bez powrotu",adultTravellers:"Dorośli",selectTravellers:"Wybierz od 1 do 9",done:"Gotowe",noAirports:"Nie znaleziono lotnisk.",economy:"Ekonomiczna",premiumEconomy:"Premium Economy",business:"Biznes",first:"Pierwsza"},
JPN:{services:["航空券","ホテル","レンタカー","アクティビティ","ヨット"],roundTrip:"往復",oneWay:"片道",from:"出発地",to:"目的地",departure:"出発",return:"帰着",travellers:"旅行者",traveller:"旅行者",cabinClass:"座席クラス",searchFlights:"航空券を検索",noReturnDate:"復路なし",adultTravellers:"大人",selectTravellers:"1〜9名を選択",done:"完了",noAirports:"該当する空港がありません。",economy:"エコノミー",premiumEconomy:"プレミアムエコノミー",business:"ビジネス",first:"ファースト"},
ZHO_CN:{services:["航班","酒店","租车","活动","游艇"],roundTrip:"往返",oneWay:"单程",from:"出发地",to:"目的地",departure:"出发",return:"返回",travellers:"旅客",traveller:"旅客",cabinClass:"舱位",searchFlights:"搜索航班",noReturnDate:"无返程",adultTravellers:"成人旅客",selectTravellers:"选择1至9名旅客",done:"完成",noAirports:"未找到机场。",economy:"经济舱",premiumEconomy:"高级经济舱",business:"商务舱",first:"头等舱"},
ZHO_TW:{services:["航班","飯店","租車","活動","遊艇"],roundTrip:"來回",oneWay:"單程",from:"出發地",to:"目的地",departure:"出發",return:"返回",travellers:"旅客",traveller:"旅客",cabinClass:"艙等",searchFlights:"搜尋航班",noReturnDate:"無回程",adultTravellers:"成人旅客",selectTravellers:"選擇1至9名旅客",done:"完成",noAirports:"找不到機場。",economy:"經濟艙",premiumEconomy:"豪華經濟艙",business:"商務艙",first:"頭等艙"},
KOR:{services:["항공편","호텔","렌터카","액티비티","요트"],roundTrip:"왕복",oneWay:"편도",from:"출발지",to:"도착지",departure:"출발",return:"귀국",travellers:"여행자",traveller:"여행자",cabinClass:"좌석 등급",searchFlights:"항공편 검색",noReturnDate:"귀국일 없음",adultTravellers:"성인 여행자",selectTravellers:"1~9명 선택",done:"완료",noAirports:"공항을 찾지 못했습니다.",economy:"이코노미",premiumEconomy:"프리미엄 이코노미",business:"비즈니스",first:"퍼스트"}
};
const FALLBACKS=["NOR","FIN","SWE","DAN","CES","HUN","RON","ELL","BUL","LAV","UKR","HIN","IND","MSA","THA","EST","HRV","LIT","SLK","SRP","SLV","VIE","FIL","ISL"];
for(const k of FALLBACKS) C[k]=EN;
C.SPA_MX=C.SPA;C.POR_PT=C.POR;C.POR_BR=C.POR;
const aliases:Record<string,string>={EN:"ENG_US",ENG:"ENG_US",AR:"ARA",FR:"FRA",ES:"SPA",PT:"POR",ZH:"ZHO_CN"};
export function normalizeLanguage(v:unknown){const r=String(v||"").trim().toUpperCase().replace(/-/g,"_");return aliases[r]||r||"ENG_US";}
export function useVoylmeHomeLocale(){const[language,setLanguage]=useState("ENG_US");useEffect(()=>{const sync=()=>setLanguage(normalizeLanguage(localStorage.getItem(VOYLME_STORAGE.language)));const change=(e:Event)=>setLanguage(normalizeLanguage((e as CustomEvent).detail));sync();window.addEventListener(VOYLME_EVENTS.languageChange,change);window.addEventListener("storage",sync);window.addEventListener("focus",sync);return()=>{window.removeEventListener(VOYLME_EVENTS.languageChange,change);window.removeEventListener("storage",sync);window.removeEventListener("focus",sync);};},[]);return useMemo(()=>({language,copy:C[normalizeLanguage(language)]||EN,isRtl:normalizeLanguage(language)==="ARA"}),[language]);}
